name: Update Script

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cURL and base64
        run: |
          sudo apt-get update
          sudo apt-get install -y curl coreutils

      - name: Get changed files
        id: get-changed-files
        run: |
          commit_sha=$(git rev-parse HEAD)
          changed_files=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                             https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$commit_sha | \
                             jq -r '.files[].filename')
          echo "::set-output name=files::$changed_files"

      - name: Run script
        run: |
          files=${{ steps.get-changed-files.outputs.files }}

          if [[ -z $files ]]; then
            echo "No file changes detected."
            exit 0
          fi

          for file in $files; do
            scriptId=$(echo -n "$file" | md5sum | awk '{print $1}')
            content=$(base64 -w 0 "$file")
            payload="{ \"script_id\": \"$scriptId\", \"text\": \"$content\" }"
            response=$(curl --header "Content-Type: application/json" \
                             --request POST \
                             --data "$payload" \
                             https://scriptserverelias.000webhostapp.com/upload.php)
            echo "$response"
          done
