name: Update Script

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set random script ID
        id: set-script-id
        run: echo "SCRIPT_ID=$(shuf -i 100000-999999 -n 1)" >> $GITHUB_ENV

      - name: Install cURL and base64
        run: |
          sudo apt-get update
          sudo apt-get install -y curl coreutils

      - name: Run script
        run: |
          files=$(git diff --name-only HEAD^ HEAD)
          scriptId=$SCRIPT_ID

          for file in $files; do
            content=$(base64 -w 0 "$file")
            payload="{ \"script_id\": \"$scriptId\", \"text\": \"$content\" }"
            response=$(curl --header "Content-Type: application/json" \
                             --request POST \
                             --data "$payload" \
                             https://scriptserverelias.000webhostapp.com/upload.php)
            echo "$response"
          done
