name: Update Script

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cURL and md5sum
        run: |
          sudo apt-get update
          sudo apt-get install -y curl coreutils

      - name: Get previous commit hash
        id: get-previous-commit
        run: |
          previous_commit=$(git rev-parse HEAD^)
          echo "::set-output name=commit::$previous_commit"

      - name: Get changed files
        id: get-changed-files
        run: |
          previous_commit=${{ steps.get-previous-commit.outputs.commit }}
          changed_files=$(git diff --name-only $previous_commit --)
          echo "::set-output name=files::$changed_files"

      - name: Run script
        run: |
          files=${{ steps.get-changed-files.outputs.files }}

          if [[ -z $files ]]; then
            echo "No file changes detected."
            exit 0
          fi

          for file in $files; do
            fileName=$(basename "$file")
            scriptId=$(echo -n "$fileName" | md5sum | awk '{print $1}' | tr -dc '0-9' | head -c 5)
            content=$(base64 -w 0 "$file")

            payload="{ \"script_id\": \"$scriptId\", \"text\": \"$content\" }"
            response=$(curl --header "Content-Type: application/json" \
                             --request POST \
                             --data "$payload" \
                             https://scriptserverelias.000webhostapp.com/upload.php)
            echo "$response"
          done
