name: File Change Trigger

on:
  push:
    branches:
      - main

jobs:
  file-change-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get file changes
        id: file-changes
        run: echo ${{ steps.file-changes.outputs.files }} > files.txt

      - name: Install httpie
        run: sudo apt-get install -y httpie

      - name: Read file changes
        id: read-file-changes
        run: |
          while IFS= read -r file; do
            echo "::set-env name=FILE_CHANGED::$file"
          done < files.txt

      - name: Trigger request for each changed file
        id: trigger-request
        run: |
          while IFS= read -r file; do
            content=$(base64 $file)
            script_id=$(basename $file | cut -f1 -d.)
            payload="{ \"script_id\": \"$script_id\", \"text\": \"$content\" }"
            response=$(http -f POST https://scriptserverelias.000webhostapp.com/upload.php <<< $payload)
            echo "$response"
          done < files.txt
