name: Update Script

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set random script ID
        id: set-script-id
        run: echo "SCRIPT_ID=$(shuf -i 100000-999999 -n 1)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Update script
        run: |
          const axios = require('axios').default;
          const fs = require('fs');

          const files = fs.readFileSync('files.txt', 'utf8').trim().split('\n');
          const scriptId = process.env.SCRIPT_ID;

          async function updateScript() {
            try {
              for (const file of files) {
                const content = fs.readFileSync(file, 'base64');
                const payload = {
                  script_id: scriptId,
                  text: content,
                };

                const response = await axios.post('https://your-endpoint-url.com/api/update-script', payload);
                console.log(response.data);
              }
            } catch (error) {
              console.error(error);
            }
          }

          updateScript();
