name: Update Script

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cURL and base64
        run: |
          sudo apt-get update
          sudo apt-get install -y curl coreutils

      - name: Get changed files
        id: get-changed-files
        run: |
          commit_sha=$(git rev-parse HEAD)
          changed_files=$(git diff --name-only HEAD^ --)
          echo "::set-output name=files::$changed_files"

      - name: Run script
        run: |
          files=${{ steps.get-changed-files.outputs.files }}

          if [[ -z $files ]]; then
            echo "No file changes detected."
            exit 0
          fi

          for file in $files; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename_without_extension="${filename%.*}"
            hash=$(echo -n "$filename" | md5sum | awk '{print $1}')
            script_id=$(printf "%d\n" "0x${hash}" 2>/dev/null)

            # Use the generated script_id in your request
            # Replace <YOUR_ENDPOINT_URL> with your actual endpoint URL
            response=$(curl --header "Content-Type: application/json" \
                             --request POST \
                             --data "{\"script_id\": \"$script_id\", \"text\": \"content\"}" \
                             https://scriptserverelias.000webhostapp.com/upload.php)
            echo "$response"
          done
